package top.niunaijun.blackbox.root;

public enum VirtualRootCapability {
    LIBSU_SHELL,
    LIBSU_ROOT_SERVICE,
    LIST_VIRTUAL_PACKAGES,
    READ_VIRTUAL_APK,
    READ_VIRTUAL_APP_DATA,
    WRITE_VIRTUAL_APP_DATA,
    INSTALL_VIRTUAL_PACKAGE,
    STOP_VIRTUAL_PACKAGE,
    READ_VIRTUAL_PERMISSION_STATE,
    WRITE_VIRTUAL_PERMISSION_STATE
}
